### ISSUE TITLE
question about line 23th~26th in domain-adaptation-toolbox/ToRelease_GFK/GFK.m

### ISSUE THREAD

**Issue by mmgongnpu** [viggin/domain-adaptation-toolbox#2]
Hi, I have a question about the code in line 23th~26th in domain-adaptation-toolbox/ToRelease_GFK/GFK.m, that is,

B1 = 0.5.*diag(1+sin(2*theta)./2./max(theta,eps));
B2 = 0.5.*diag((-1+cos(2*theta))./2./max(theta,eps));
B3 = B2;
B4 = 0.5.*diag(1-sin(2*theta)./2./max(theta,eps));

I checked the corresponding formula (Eq. 6) in the article "Geodesic Flow Kernel for Unsupervised Domain Adaptation" and found that there was no factor 0.5 in the formula.

I sincerely hope you can spend some time to answer my doubts. Thanks.

**Comment by viggin** [comment]
You can ask this guy: http://www-scf.usc.edu/~boqinggo/
He wrote the GFK.

**Comment by mmgongnpu** [comment]
> You can ask this guy: http://www-scf.usc.edu/~boqinggo/
> He wrote the GFK.
Hi, I clicked this link, however it was shown "the requested URL /~boqinggo/ was not found on this server." So could you do me a favor to figure it out?
